server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.6.181:3306/exam
    username: root
    password: test
mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: info.mysuite.domain